// Gedeelde catalogus voor badges en trofeeën — gebruikt door de homepage en /admin.
window.KWIM_CATALOGUS = {
  // De emoji-catalogus is leeg: de enige winbare badges zijn de geüploade
  // patch-afbeeldingen (badgeDefs in de state), beheerd via /admin.
  badges: [],
  trofeeen: [
    { id: "gouden-kwim",   emoji: "🏆", naam: "De Gouden Kwim" },
    { id: "zilveren-mango", emoji: "🥭", naam: "De Zilveren Mango" },
    { id: "bronzen-oog",   emoji: "👁️", naam: "Het Bronzen Oog" },
    { id: "gouden-schoen", emoji: "👟", naam: "De Gouden Schoen" },
    { id: "infantino",     emoji: "🎩", naam: "De Infantino Bokaal" },
    { id: "comeback",      emoji: "🔥", naam: "Comeback van het Jaar" },
    { id: "fairplay",      emoji: "🤝", naam: "Fair Play Award" },
    { id: "pollepel",      emoji: "🥄", naam: "De Houten Pollepel" }
  ],
  // emoji-keuze voor eigen trofeeën in het admin-paneel
  emojis: ["🏆", "🥇", "🥈", "🥉", "🍾", "⚽", "🥭", "👁️", "🎖️", "💀", "🦆", "🧨", "🍟", "🚑", "🛎️", "🪩"],
  // landen-catalogus voor de "land van het team"-instelling — voetballanden, op naam gesorteerd
  landen: [
    { code: "DZ", naam: "Algerije",             vlag: "🇩🇿" },
    { code: "AR", naam: "Argentinië",            vlag: "🇦🇷" },
    { code: "AU", naam: "Australië",             vlag: "🇦🇺" },
    { code: "BE", naam: "België",                vlag: "🇧🇪" },
    { code: "BA", naam: "Bosnië en Herzegovina",  vlag: "🇧🇦" },
    { code: "BR", naam: "Brazilië",              vlag: "🇧🇷" },
    { code: "BG", naam: "Bulgarije",             vlag: "🇧🇬" },
    { code: "CA", naam: "Canada",                vlag: "🇨🇦" },
    { code: "CL", naam: "Chili",                 vlag: "🇨🇱" },
    { code: "CN", naam: "China",                 vlag: "🇨🇳" },
    { code: "CO", naam: "Colombia",              vlag: "🇨🇴" },
    { code: "CR", naam: "Costa Rica",            vlag: "🇨🇷" },
    { code: "HR", naam: "Kroatië",               vlag: "🇭🇷" },
    { code: "DK", naam: "Denemarken",            vlag: "🇩🇰" },
    { code: "DE", naam: "Duitsland",             vlag: "🇩🇪" },
    { code: "EC", naam: "Ecuador",               vlag: "🇪🇨" },
    { code: "EG", naam: "Egypte",                vlag: "🇪🇬" },
    { code: "FI", naam: "Finland",               vlag: "🇫🇮" },
    { code: "FR", naam: "Frankrijk",             vlag: "🇫🇷" },
    { code: "GH", naam: "Ghana",                 vlag: "🇬🇭" },
    { code: "GR", naam: "Griekenland",           vlag: "🇬🇷" },
    { code: "HU", naam: "Hongarije",             vlag: "🇭🇺" },
    { code: "IS", naam: "IJsland",               vlag: "🇮🇸" },
    { code: "IN", naam: "India",                 vlag: "🇮🇳" },
    { code: "ID", naam: "Indonesië",             vlag: "🇮🇩" },
    { code: "IR", naam: "Iran",                  vlag: "🇮🇷" },
    { code: "IE", naam: "Ierland",               vlag: "🇮🇪" },
    { code: "IL", naam: "Israël",                vlag: "🇮🇱" },
    { code: "IT", naam: "Italië",                vlag: "🇮🇹" },
    { code: "CI", naam: "Ivoorkust",             vlag: "🇨🇮" },
    { code: "JM", naam: "Jamaica",               vlag: "🇯🇲" },
    { code: "JP", naam: "Japan",                 vlag: "🇯🇵" },
    { code: "CM", naam: "Kameroen",              vlag: "🇨🇲" },
    { code: "KE", naam: "Kenia",                 vlag: "🇰🇪" },
    { code: "MA", naam: "Marokko",               vlag: "🇲🇦" },
    { code: "MX", naam: "Mexico",                vlag: "🇲🇽" },
    { code: "NL", naam: "Nederland",             vlag: "🇳🇱" },
    { code: "NZ", naam: "Nieuw-Zeeland",         vlag: "🇳🇿" },
    { code: "NG", naam: "Nigeria",               vlag: "🇳🇬" },
    { code: "NO", naam: "Noorwegen",             vlag: "🇳🇴" },
    { code: "AT", naam: "Oostenrijk",            vlag: "🇦🇹" },
    { code: "PA", naam: "Panama",                vlag: "🇵🇦" },
    { code: "PY", naam: "Paraguay",              vlag: "🇵🇾" },
    { code: "PE", naam: "Peru",                  vlag: "🇵🇪" },
    { code: "PL", naam: "Polen",                 vlag: "🇵🇱" },
    { code: "PT", naam: "Portugal",              vlag: "🇵🇹" },
    { code: "QA", naam: "Qatar",                 vlag: "🇶🇦" },
    { code: "RO", naam: "Roemenië",              vlag: "🇷🇴" },
    { code: "RU", naam: "Rusland",               vlag: "🇷🇺" },
    { code: "SA", naam: "Saudi-Arabië",          vlag: "🇸🇦" },
    { code: "SN", naam: "Senegal",               vlag: "🇸🇳" },
    { code: "RS", naam: "Servië",                vlag: "🇷🇸" },
    { code: "SK", naam: "Slowakije",             vlag: "🇸🇰" },
    { code: "SI", naam: "Slovenië",              vlag: "🇸🇮" },
    { code: "ES", naam: "Spanje",                vlag: "🇪🇸" },
    { code: "KR", naam: "Zuid-Korea",            vlag: "🇰🇷" },
    { code: "ZA", naam: "Zuid-Afrika",           vlag: "🇿🇦" },
    { code: "SE", naam: "Zweden",                vlag: "🇸🇪" },
    { code: "CH", naam: "Zwitserland",           vlag: "🇨🇭" },
    { code: "TN", naam: "Tunesië",               vlag: "🇹🇳" },
    { code: "TR", naam: "Turkije",               vlag: "🇹🇷" },
    { code: "GB", naam: "Verenigd Koninkrijk",   vlag: "🇬🇧" },
    { code: "US", naam: "Verenigde Staten",      vlag: "🇺🇸" },
    { code: "UY", naam: "Uruguay",               vlag: "🇺🇾" },
    { code: "VE", naam: "Venezuela",             vlag: "🇻🇪" }
  ]
};
